apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage-volume-claim
  labels:
    deployment: redis-storage-volume-claim
spec:
  storageClassName: "azurefile-csi-premium"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
