apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    # ports that this service should serve on
    - name: redis-service
      protocol: TCP
      port: 6379
      targetPort: 6379